tokenizer: roberta-large
plm: roberta-large
lm_size: 1024
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
max_sequence_length: 512
cached_dir: "cache/PromptRefiner/"
weight_decay: 0.01
learning_rate: 0.00005
num_warmup_steps: 3000
gradient_accumulation_steps: 1
num_train_epochs: 3
dropout: 0.1
max_grad_norm: 5
run_sft: true
run_rlt: true
run_online_eval: true
run_offline_eval: true
num_train_rl_epochs: 6
sampled_times: 100
rl_learning_rate: 0.000001
uniform_weights: false
