dataset_name: es_conv
train_data_path: data/es_data/esc/esc-train.txt
dev_data_path: data/es_data/esc/esc-valid.txt
test_data_path: data/es_data/esc/esc-test.txt
n_goals: 8
log: true
save_goal_path: data/es_data/esc/goal.pkl
save_dev_simulator_path: data/es_data/esc/dev_sim.pkl
save_test_simulator_path: data/es_data/esc/test_sim.pkl
save_action: False
load_action: true
save_train_convs: true
num_train_cases: 1040
num_dev_cases: 130
num_test_cases: 130
terminated_action: "Say goodbye"