dataset_name: p4g
train_data_path: data/pg_data/p4g/p4g-train.txt
dev_data_path: data/pg_data/p4g/p4g-valid.txt
test_data_path: data/pg_data/p4g/p4g-test.txt
n_goals: 8
log: true
save_goal_path: data/pg_data/p4g/goal.pkl
save_dev_simulator_path: data/pg_data/p4g/dev_sim.pkl
save_test_simulator_path: data/pg_data/p4g/test_sim.pkl
save_action: False
load_action: true
save_train_convs: true
num_train_cases: 180
num_dev_cases: 60
num_test_cases: 60
terminated_action: "Say goodbye"